name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      env:
        PYTHONPATH: "${{ github.workspace }}"
        FLASK_ENV: testing
        GITHUB_ACTIONS: "true"  # Важно для активации CI-режима
      run: |
        pytest tests/ -v --cov=atelie --cov-report=xml