name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r pythonProject/requirements.txt  # Убедитесь, что файл существует
        pip install gunicorn  # Для деплоя

    - name: Verify Flask app
      run: |
        python -c "from Atelie.app import app; print('App initialized successfully')"  # Укажите правильный путь к app
