name: CI Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      env:
        FLASK_ENV: testing
        PYTHONPATH: "${{ github.workspace }}/pythonProject"
      run: |
        pytest pythonProject/atelie/tests/ -v --cov=pythonProject/atelie --cov-report=xml