name: CI Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ./pythonProject
        pip install pytest pytest-cov
        pip install -r ./pythonProject/requirements.txt

    - name: Run tests
      env:
        FLASK_APP: atelie.app
        FLASK_ENV: testing
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        SECRET_KEY: test-secret-key
      run: |
        cd pythonProject
        pytest atelie/tests/ -v --cov=atelie --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v3